services:
  pg-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=jkop
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=baltimoreDB
    volumes:
      - "./baltimore_crime_data:/var/lib/postgresql/data:rw"
    ports:
      - "5431:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"